# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: COM 220 - 002 (Angella Billings)
email: jmbeach1@crimson.ua.edu
description: > # this means to ignore newlines until "baseurl:"
    A website with notes and Quizlets for The UA's COM 220 - 002 class taught by Professor Billings.
baseurl: "/COM220-002" # the subpath of your site, e.g. /blog
url: "http://jmbeach.github.io/COM220-002"

# Build settings
markdown: kramdown
